import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SiteMap from "./Common/sitemap";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Umbraco NextJS Demo App",
  description: "Generated by Etive Mor",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col p-24">
        <div>
            <SiteMap />
          </div>
        {children}

  
        </main>
      </body>


    </html>
  );
}
