import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children
}:
  Readonly<{
    children: React.ReactNode;
  }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="text-center p-5">This site is a demo static site generated by <Link href='https://nextjs.org/' target="_blank"><span className='underline italic hover:font-bold'>next.js</span></Link> with an <Link href='https://umbraco.com/' target="_blank"><span className='underline italic hover:font-bold'>Umbraco</span></Link> backoffice.
        
         Created by <Link href='https://www.etive-mor.com/' target="_blank"><span className='underline italic hover:font-bold'>Etive Mòr</span></Link>.</div>

        <main className="flex min-h-screen flex-col p-24 max-w-screen-2xl">
          {children}
        </main>

      </body>
    </html>
  );
}

export const metadata: Metadata =  {
  metadataBase: new URL('http://localhost:3000/'),
  title: {
    template: '%s | Demo Umbraco NextJS Site',
    default: 'Demo Umbraco NextJS Site - A demo website created with NextJS and Umbraco'
  },
  description: 'A demo website created with NextJS and Umbraco',
  // openGraph: {
  //   title: {
  //     template: '%s | Demo Umbraco NextJS Site',
  //     default: 'Demo Umbraco NextJS Site - A demo website created with NextJS and Umbraco'
  //   },
  //   description: 'A demo website created with NextJS and Umbraco',
  // },
  // twitter: {
  //   card: 'summary_large_image',
  //   title: {
  //     template: '%s | Demo Umbraco NextJS Site',
  //     default: 'Demo Umbraco NextJS Site - A demo website created with NextJS and Umbraco'
  //   },
  // },
}